import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        <header>
          <nav>
            <ul className="flex bg-slate-200 py-4 px-2 gap-6 text-lg tracking-wide">
              <li>
                <Link href="/">SSG</Link>
              </li>
              <li>
                <Link href="/isr">ISR</Link>
              </li>
              <li>
                <Link href="/ssr">SSR</Link>
              </li>
              <li>
                <Link href="/csr">CSR</Link>
              </li>
            </ul>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
